name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs: 
  build: 
    name: build APK
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkout@v4

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' #might change to beta

    - name: install dependencies
      working-directory: ./flutter_todo_app
      run: flutter pub get

    - name: run test
      working-directory: ./flutter_todo_app
      run: flutter test

    - name: build flutter web
      working-directory: ./flutter_todo_app
      run: flutter build web

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./flutter_todo_app/build/web/
       
    
