on: push
name: CI/CD Pipeline
jobs: 
  build: 
    name: build APK
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: install dependencies
      run: flutter pub get

    - name: run test
      run: flutter test

    - name: build flutter web
      run: flutter build web

    - name: deploy 
      uses: peaceiris/actions-gh-pages@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/build/web/
    
