on: push
name: CI/CD Pipeline

jobs: 
  build: 
    name: build APK
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkout@v1

    - name: node.js setup
      uses: actions/setup-node@v1
      with:
        node-version: '20'
        
    - name: java setup
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: install dependencies
      working-directory: ./default_flutter_app
      run: flutter pub get

    - name: run test
      working-directory: ./default_flutter_app
      run: flutter test

    - name: build flutter web
      working-directory: ./default_flutter_app
      run: flutter build web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Web Release
      uses: actions/download-artifact@v2
      with:
        name: web-release

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
       
    
